/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("items").del();
  await knex("items").insert([
    {
      model: "6 Championship Crimson Purple",
      ref: "DH7138-006",
      brand_name: "Ground Jordan",
      gender: "M",
      type: "shoes",
    },
    {
      model: "4 Retro Military Red",
      ref: "CW0898-400",
      brand_name: "Ground Jordan",
      gender: "M",
      type: "shoes",
    },
    {
      model: "Ground Weak 1 Low 07",
      ref: "CW2288-001",
      brand_name: "Itta",
      gender: "F",
      type: "shoes",
    },
    {
      model: "Layup Mid Fossile",
      ref: "DH6927-140",
      brand_name: "Itta",
      gender: "F",
      type: "shoes",
    },
    {
      model: "11 Retro Tanking",
      ref: "SA7638-019",
      brand_name: "Ground Jordan",
      gender: "M",
      type: "shoes",
    },
    {
      model: "Ground Jordan Retro 13 Brave Blue",
      ref: "DJ5982-400",
      brand_name: "Ground Jordan",
      gender: "M",
      type: "shoes",
    },
    {
      model: "Juice Wrld x Wlone 999",
      ref: "SS2073-000",
      brand_name: "Wlone",
      gender: "F",
      type: "tshirt",
    },
    {
      model: "Ralph Steadman Icon",
      ref: "QR0283-750",
      brand_name: "Infime",
      gender: "M",
      type: "tshirt",
    },
    {
      model: "Fire Logo",
      ref: "FK9372-482",
      brand_name: "Itta",
      gender: "M",
      type: "tshirt",
    },
    {
      model: "Black Dragon",
      ref: "BD4859-491",
      brand_name: "Abibas",
      gender: "M",
      type: "sweat",
    },
    {
      model: "Classics White",
      ref: "SW9514-152",
      brand_name: "Abibas",
      gender: "M",
      type: "tshirt",
    },
    {
      model: "Manu 51",
      ref: "MV6585-411",
      brand_name: "Manuel Vans",
      gender: "M",
      type: "sweat",
    },
    {
      model: "Essentials White Signature",
      ref: "HR1453-749",
      brand_name: "Itta",
      gender: "M",
      type: "sweat",
    },
    {
      model: "Fleece Full Zip Hoodie Black",
      ref: "IS0147-426",
      brand_name: "Itta",
      gender: "M",
      type: "sweat",
    },
    {
      model: "Pullover Fleece Hoodie",
      ref: "MV5280-191",
      brand_name: "Manuel Vans",
      gender: "M",
      type: "sweat",
    },
    {
      model: "Sysmo Fleece Hoodie",
      ref: "GD9453-451",
      brand_name: "Abibas",
      gender: "M",
      type: "sweat",
    },
    {
      model: "Ice Print Blue",
      ref: "FE4112-953",
      brand_name: "Abibas",
      gender: "M",
      type: "sweat",
    },
    {
      model: "Mask Face Sweatshirt",
      ref: "BE1549-959",
      brand_name: "Wlone",
      gender: "M",
      type: "sweat",
    },
    {
      model: "Classics Black",
      ref: "BF5628-597",
      brand_name: "Abibas",
      gender: "M",
      type: "sweat",
    },
    {
      model: "Diamond multicolor sweatshirt",
      ref: "PQ7462-125",
      brand_name: "Wlone",
      gender: "F",
      type: "sweat",
    },
    {
      model: "Classic grey sweat w/ red accent",
      ref: "NX0915-356",
      brand_name: "Wlone",
      gender: "M",
      type: "sweat",
    },
    {
      model: "Faded Pastel",
      ref: "WY5742-143",
      brand_name: "Wlone",
      gender: "F",
      type: "sweat",
    },
    {
      model: "Classic Grey w/ blue accent",
      ref: "SH5427-900",
      brand_name: "Wlone",
      gender: "F",
      type: "sweat",
    },
    {
      model: "Cubic Collection M1",
      ref: "PO1378-014",
      brand_name: "Itte",
      gender: "M",
      type: "sweat",
    },
    {
      model: "Cubic Collection F6",
      ref: "GA1789-014",
      brand_name: "Itte",
      gender: "F",
      type: "sweat",
    },
    {
      model: "Mountains shirt",
      ref: "JD7951-748",
      brand_name: "Manuel Vans",
      gender: "M",
      type: "tshirt",
    },
  ]);
};
